version: 2.1
jobs:
  chromedriver:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: sudo apt-get update && sudo apt-get install -y libnss3-dev
            - run: npm install
            - run: yarn install
      - run: yarn test
  safari:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: sudo apt-get update && sudo apt-get install -y libnss3-dev
            - run: npm install
            - run: yarn install
      - run: yarn test
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - chromedriver
      - safari