version: 2.1
orbs:
  saucelabs: saucelabs/sauce-connect@volatile
  node: circleci/node@volatile
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - saucelabs/install:
                version: 4.5.4
            - run: echo 127.0.0.1 sauce.local | sudo tee -a /etc/hosts
      - run:
          name: Open Sauce Connect Proxy Tunnel
          command: |
            : ${SAUCELABS_USER:?"Required Env Variable not found!"}
            : ${SAUCELABS_KEY:?"Required Env Variable not found!"}
            # startup saucelabs tunnel as background task (its a blocking command)
            sc -u ${SAUCELABS_USER} -k ${SAUCELABS_KEY} -i stitches -x https://eu-central-1.saucelabs.com/rest/v1 -l sauce_connect.log -v &
            # wait for sauce tunnel up to 1 minute
            wget --retry-connrefused --no-check-certificate -T 60 localhost:4445
      - run: npm start
      - run: node ./node_modules/.bin/nightwatch -c nightwatch-sauce.conf.js -e chrome
      - saucelabs/close_tunnel

# workflows:
#   version: 2.1
#   build_and_test:
#     jobs:
#       - build
#       - saucelabs/with_proxy:
#           requires:
#             - build
#           version: 4.5.4
#           steps:
#             - run: npm start
#             - run: node ./node_modules/.bin/nightwatch -c nightwatch-sauce.conf.js -e safari,chrome,chromeMac,firefox,iphone,pixel,galaxys9,ucbrowser

  # jobs:
  #   - build:
  #     executor:
  #       name: node/default
  #       tag: '10.4'
  #     steps:
  #       - node/with-cache:
  #         steps:
  #           - checkout
  #           - run: npm install
  #       - saucelabs/with_proxy:
  #         version: 4.5.4
  #         steps:
  #           - run: npm start
  #           - run: node ./node_modules/.bin/nightwatch -c nightwatch-sauce.conf.js -e safari,chrome,chromeMac,firefox,iphone,pixel,galaxys9,ucbrowser

